package Backend.ServiceLayer.ServiceLayerHR;

public enum PermissionLevel {
    SYSTEMMANAGER,
    HRMANAGER,
    TRANSPORTMANAGER,
    TRANSPORTEMPLOYEE,
    REGULAREMPLOYEE,
    WAREHOUSEEMPLOYEE,
    STOREMANAGER,
    SUPPLIERMANAGER
}
